name: CI Pipeline

on:
  pull_request:
    branches: [ main, dev ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16'  # Use the node version that matches your development environment

      - name: Cache Node Modules
        uses: actions/cache@v2
        with:
          # npm cache files are stored in `~/.npm` on Unix, or `%AppData%/npm-cache` on Windows
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
            ${{ runner.os }}-

      - name: Install Dependencies
        run: npm ci

      - name: Lint
        run: npm run lint  # Make sure this script is defined in your package.json

      - name: Run Tests
        run: npm test  # Make sure the test command matches what you have in package.json

